POST http://localhost:5000/it4788/auth/login?phonenumber=0988168182&password=123456
Content-Type: application/json

{
    "image": ["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4zLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvnQurowAAAB9SURBVHic7dw9CsJAEIDhGe/MZO3sQ+AQHGjiQfQFQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQzFQ8QMQz"]
}